/*
  Close the remaining role-normalization privilege-escalation bypass.

  20260713140000 rejected canonical super-admin roles but did not trim the
  value before comparing it. current_user_role() did trim it, so an owner
  could write a value such as ' super_admin ' that the trigger accepted and
  the authorization helpers later treated as a platform administrator.

  This migration makes role normalization identical everywhere, records all
  existing privileged accounts for an explicit authorization review, and
  quarantines whitespace-wrapped privileged roles because they may have been
  created through the bypass.
*/

CREATE OR REPLACE FUNCTION public.normalize_app_role(p_role text)
RETURNS text
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
SET search_path = public
AS $$
  SELECT replace(lower(btrim(COALESCE(p_role, ''))), '-', '_');
$$;

CREATE OR REPLACE FUNCTION public.current_user_role()
RETURNS text
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  role_value text;
BEGIN
  IF auth.uid() IS NULL OR to_regclass('public.usuarios') IS NULL THEN
    RETURN '';
  END IF;

  EXECUTE 'SELECT COALESCE(rol, role, tipo, user_role, '''') FROM public.usuarios WHERE id = $1 LIMIT 1'
    INTO role_value
    USING auth.uid();

  RETURN public.normalize_app_role(role_value);
EXCEPTION
  WHEN undefined_column THEN
    EXECUTE 'SELECT COALESCE(rol, '''') FROM public.usuarios WHERE id = $1 LIMIT 1'
      INTO role_value
      USING auth.uid();

    RETURN public.normalize_app_role(role_value);
END;
$$;

CREATE TABLE IF NOT EXISTS public.platform_role_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id uuid NOT NULL,
  negocio_id uuid,
  raw_role text NOT NULL,
  normalized_role text NOT NULL,
  reason text NOT NULL,
  review_status text NOT NULL DEFAULT 'pending'
    CHECK (review_status IN ('pending', 'authorized', 'revoked')),
  captured_at timestamptz NOT NULL DEFAULT now(),
  reviewed_at timestamptz,
  reviewed_by uuid
);

ALTER TABLE public.platform_role_audit ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "platform admins read role audit" ON public.platform_role_audit;
CREATE POLICY "platform admins read role audit"
  ON public.platform_role_audit
  FOR SELECT
  TO authenticated
  USING (public.is_platform_admin());

DROP POLICY IF EXISTS "platform admins review role audit" ON public.platform_role_audit;
CREATE POLICY "platform admins review role audit"
  ON public.platform_role_audit
  FOR UPDATE
  TO authenticated
  USING (public.is_platform_admin())
  WITH CHECK (public.is_platform_admin());

REVOKE INSERT, DELETE ON public.platform_role_audit FROM anon, authenticated;
GRANT SELECT, UPDATE ON public.platform_role_audit TO authenticated;

DO $migration$
BEGIN
  IF to_regclass('public.usuarios') IS NOT NULL THEN
    INSERT INTO public.platform_role_audit (
      usuario_id,
      negocio_id,
      raw_role,
      normalized_role,
      reason,
      review_status
    )
    SELECT
      usuario.id,
      usuario.negocio_id,
      usuario.rol,
      public.normalize_app_role(usuario.rol),
      CASE
        WHEN usuario.rol IS DISTINCT FROM btrim(usuario.rol)
          THEN 'noncanonical_whitespace_privileged_role'
        ELSE 'existing_platform_admin_review'
      END,
      CASE
        WHEN usuario.rol IS DISTINCT FROM btrim(usuario.rol)
          THEN 'revoked'
        ELSE 'pending'
      END
    FROM public.usuarios AS usuario
    WHERE public.normalize_app_role(usuario.rol) IN ('superadmin', 'super_admin')
      AND NOT EXISTS (
        SELECT 1
        FROM public.platform_role_audit AS audit
        WHERE audit.usuario_id = usuario.id
          AND audit.raw_role = usuario.rol
      );

    -- The old trigger would reject this defensive cleanup because migrations
    -- do not execute with an authenticated platform-admin JWT. Recreate it
    -- immediately below, inside the same transaction.
    DROP TRIGGER IF EXISTS protect_user_role_update_trigger ON public.usuarios;

    UPDATE public.usuarios
    SET rol = 'security_review'
    WHERE public.normalize_app_role(rol) IN ('superadmin', 'super_admin')
      AND rol IS DISTINCT FROM btrim(rol);
  END IF;
END
$migration$;

CREATE OR REPLACE FUNCTION public.protect_user_role_update()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  old_row jsonb;
  new_row jsonb;
  old_role text;
  new_role text;
BEGIN
  old_row := to_jsonb(OLD);
  new_row := to_jsonb(NEW);
  old_role := public.normalize_app_role(COALESCE(old_row->>'rol', old_row->>'role', old_row->>'tipo', old_row->>'user_role', ''));
  new_role := public.normalize_app_role(COALESCE(new_row->>'rol', new_row->>'role', new_row->>'tipo', new_row->>'user_role', ''));

  IF auth.role() = 'service_role' OR public.is_platform_admin() THEN
    RETURN NEW;
  END IF;

  IF new_role IN ('superadmin', 'super_admin') THEN
    RAISE EXCEPTION 'Solo un super administrador puede asignar ese rol';
  END IF;

  IF (new_row->>'negocio_id') IS DISTINCT FROM (old_row->>'negocio_id') THEN
    RAISE EXCEPTION 'No tienes permiso para reasignar el negocio de un usuario';
  END IF;

  IF NOT public.can_manage_current_business() THEN
    IF (new_row->>'rol') IS DISTINCT FROM (old_row->>'rol')
      OR (new_row->>'role') IS DISTINCT FROM (old_row->>'role')
      OR (new_row->>'tipo') IS DISTINCT FROM (old_row->>'tipo')
      OR (new_row->>'user_role') IS DISTINCT FROM (old_row->>'user_role')
      OR (new_row->>'activo') IS DISTINCT FROM (old_row->>'activo')
      OR (new_row->>'is_active') IS DISTINCT FROM (old_row->>'is_active')
    THEN
      RAISE EXCEPTION 'No tienes permiso para cambiar roles o permisos de usuario';
    END IF;
  END IF;

  IF public.is_business_admin() THEN
    IF old_role IN ('owner', 'dueno', 'dueño', 'superadmin', 'super_admin')
      OR new_role IN ('owner', 'dueno', 'dueño', 'admin', 'administrador', 'superadmin', 'super_admin')
    THEN
      RAISE EXCEPTION 'Un administrador solo puede gestionar vendedores';
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

DO $migration$
BEGIN
  IF to_regclass('public.usuarios') IS NOT NULL THEN
    DROP TRIGGER IF EXISTS protect_user_role_update_trigger ON public.usuarios;
    CREATE TRIGGER protect_user_role_update_trigger
      BEFORE UPDATE ON public.usuarios
      FOR EACH ROW
      EXECUTE FUNCTION public.protect_user_role_update();
  END IF;
END
$migration$;

GRANT EXECUTE ON FUNCTION public.current_user_role() TO authenticated;

