/*
  Inventory transformations convert packaged stock into sellable units while
  recording any damaged units as shrinkage. The RPC owns the complete write so
  the source decrement, destination increment and history row either all
  succeed or all roll back.
*/

CREATE TABLE IF NOT EXISTS public.inventory_transformations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  negocio_id uuid NOT NULL REFERENCES public.negocios(id) ON DELETE CASCADE,
  source_product_id bigint REFERENCES public.productos(id) ON DELETE SET NULL,
  destination_product_id bigint REFERENCES public.productos(id) ON DELETE SET NULL,
  source_product_name text NOT NULL,
  destination_product_name text NOT NULL,
  source_quantity numeric NOT NULL CHECK (source_quantity > 0),
  units_per_source numeric NOT NULL CHECK (units_per_source > 0),
  total_units numeric NOT NULL CHECK (total_units > 0),
  damaged_quantity numeric NOT NULL DEFAULT 0 CHECK (damaged_quantity >= 0),
  destination_quantity numeric NOT NULL CHECK (destination_quantity > 0),
  notes text,
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT inventory_transformations_distinct_products
    CHECK (source_product_id <> destination_product_id),
  CONSTRAINT inventory_transformations_quantity_balance
    CHECK (total_units = damaged_quantity + destination_quantity)
);

CREATE INDEX IF NOT EXISTS inventory_transformations_negocio_created_idx
  ON public.inventory_transformations (negocio_id, created_at DESC);

CREATE INDEX IF NOT EXISTS inventory_transformations_source_product_idx
  ON public.inventory_transformations (source_product_id);

CREATE INDEX IF NOT EXISTS inventory_transformations_destination_product_idx
  ON public.inventory_transformations (destination_product_id);

ALTER TABLE public.inventory_transformations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "inventory transformations tenant select"
  ON public.inventory_transformations;

CREATE POLICY "inventory transformations tenant select"
  ON public.inventory_transformations
  FOR SELECT
  TO authenticated
  USING (
    public.is_platform_admin()
    OR negocio_id = public.current_user_negocio_id()
  );

REVOKE INSERT, UPDATE, DELETE ON public.inventory_transformations FROM authenticated;
GRANT SELECT ON public.inventory_transformations TO authenticated;

CREATE OR REPLACE FUNCTION public.transform_inventory(
  p_source_product_id bigint,
  p_destination_product_id bigint,
  p_source_quantity numeric,
  p_units_per_source numeric,
  p_damaged_quantity numeric DEFAULT 0,
  p_notes text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_negocio_id uuid := public.current_user_negocio_id();
  v_source_stock numeric;
  v_destination_stock numeric;
  v_source_product_name text;
  v_destination_product_name text;
  v_total_units numeric;
  v_destination_quantity numeric;
  v_transformation_id bigint;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Debes iniciar sesión para transformar inventario';
  END IF;

  IF NOT public.can_manage_current_business() THEN
    RAISE EXCEPTION 'No tienes permiso para transformar inventario';
  END IF;

  IF v_negocio_id IS NULL THEN
    RAISE EXCEPTION 'Usuario sin negocio asignado';
  END IF;

  IF p_source_product_id IS NULL OR p_destination_product_id IS NULL THEN
    RAISE EXCEPTION 'Debes seleccionar los productos de origen y destino';
  END IF;

  IF p_source_product_id = p_destination_product_id THEN
    RAISE EXCEPTION 'El producto de origen y destino deben ser diferentes';
  END IF;

  IF p_source_quantity IS NULL OR p_source_quantity <= 0 THEN
    RAISE EXCEPTION 'La cantidad de origen debe ser mayor que cero';
  END IF;

  IF p_units_per_source IS NULL OR p_units_per_source <= 0 THEN
    RAISE EXCEPTION 'Las unidades por empaque deben ser mayores que cero';
  END IF;

  IF COALESCE(p_damaged_quantity, 0) < 0 THEN
    RAISE EXCEPTION 'La cantidad averiada no puede ser negativa';
  END IF;

  v_total_units := p_source_quantity * p_units_per_source;
  v_destination_quantity := v_total_units - COALESCE(p_damaged_quantity, 0);

  IF v_destination_quantity <= 0 THEN
    RAISE EXCEPTION 'Debe quedar al menos una unidad aprovechable';
  END IF;

  -- Lock both product rows in stable ID order to avoid concurrent updates and
  -- deadlocks when two transformations touch the same products.
  PERFORM id
  FROM public.productos
  WHERE id IN (p_source_product_id, p_destination_product_id)
    AND negocio_id = v_negocio_id
  ORDER BY id
  FOR UPDATE;

  SELECT COALESCE(stock, 0), nombre
  INTO v_source_stock, v_source_product_name
  FROM public.productos
  WHERE id = p_source_product_id
    AND negocio_id = v_negocio_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Producto de origen no encontrado para este negocio';
  END IF;

  SELECT COALESCE(stock, 0), nombre
  INTO v_destination_stock, v_destination_product_name
  FROM public.productos
  WHERE id = p_destination_product_id
    AND negocio_id = v_negocio_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Producto de destino no encontrado para este negocio';
  END IF;

  IF v_source_stock < p_source_quantity THEN
    RAISE EXCEPTION 'Stock insuficiente en el producto de origen. Disponible: %', v_source_stock;
  END IF;

  UPDATE public.productos
  SET stock = v_source_stock - p_source_quantity
  WHERE id = p_source_product_id
    AND negocio_id = v_negocio_id;

  UPDATE public.productos
  SET stock = v_destination_stock + v_destination_quantity
  WHERE id = p_destination_product_id
    AND negocio_id = v_negocio_id;

  INSERT INTO public.inventory_transformations (
    negocio_id,
    source_product_id,
    destination_product_id,
    source_product_name,
    destination_product_name,
    source_quantity,
    units_per_source,
    total_units,
    damaged_quantity,
    destination_quantity,
    notes,
    created_by
  )
  VALUES (
    v_negocio_id,
    p_source_product_id,
    p_destination_product_id,
    v_source_product_name,
    v_destination_product_name,
    p_source_quantity,
    p_units_per_source,
    v_total_units,
    COALESCE(p_damaged_quantity, 0),
    v_destination_quantity,
    NULLIF(trim(COALESCE(p_notes, '')), ''),
    auth.uid()
  )
  RETURNING id INTO v_transformation_id;

  RETURN jsonb_build_object(
    'id', v_transformation_id,
    'source_stock_before', v_source_stock,
    'source_stock_after', v_source_stock - p_source_quantity,
    'destination_stock_before', v_destination_stock,
    'destination_stock_after', v_destination_stock + v_destination_quantity,
    'total_units', v_total_units,
    'damaged_quantity', COALESCE(p_damaged_quantity, 0),
    'destination_quantity', v_destination_quantity
  );
END;
$$;

REVOKE ALL ON FUNCTION public.transform_inventory(bigint, bigint, numeric, numeric, numeric, text)
  FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.transform_inventory(bigint, bigint, numeric, numeric, numeric, text)
  TO authenticated;
