/*
  Partial sale returns keep the original invoice immutable while recording
  stock disposition and customer compensation in one atomic operation.
*/

CREATE TABLE IF NOT EXISTS public.sale_returns (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  negocio_id uuid NOT NULL REFERENCES public.negocios(id) ON DELETE CASCADE,
  sale_id bigint NOT NULL REFERENCES public.ventas(id) ON DELETE RESTRICT,
  client_id bigint REFERENCES public.clientes(id) ON DELETE SET NULL,
  compensation_method text NOT NULL CHECK (
    compensation_method IN ('cash_refund', 'store_credit', 'reduce_debt')
  ),
  reason text NOT NULL,
  refund_total numeric NOT NULL DEFAULT 0 CHECK (refund_total >= 0),
  restocked_quantity numeric NOT NULL DEFAULT 0 CHECK (restocked_quantity >= 0),
  damaged_quantity numeric NOT NULL DEFAULT 0 CHECK (damaged_quantity >= 0),
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  processed_by_name text NOT NULL DEFAULT 'Usuario',
  return_date date NOT NULL DEFAULT current_date,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.sale_return_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  negocio_id uuid NOT NULL REFERENCES public.negocios(id) ON DELETE CASCADE,
  return_id bigint NOT NULL REFERENCES public.sale_returns(id) ON DELETE CASCADE,
  sale_item_id bigint NOT NULL REFERENCES public.venta_items(id) ON DELETE RESTRICT,
  product_id bigint REFERENCES public.productos(id) ON DELETE SET NULL,
  product_name text NOT NULL,
  quantity numeric NOT NULL CHECK (quantity > 0),
  stock_condition text NOT NULL CHECK (stock_condition IN ('restock', 'damaged')),
  unit_price numeric NOT NULL CHECK (unit_price >= 0),
  gross_amount numeric NOT NULL CHECK (gross_amount >= 0),
  discount_amount numeric NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
  refund_amount numeric NOT NULL CHECK (refund_amount >= 0),
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Some environments received an early version of these tables before this
-- migration was tracked. Complete that schema in place without dropping or
-- replacing existing return records.
ALTER TABLE public.sale_returns
  ADD COLUMN IF NOT EXISTS processed_by_name text,
  ADD COLUMN IF NOT EXISTS return_date date;

UPDATE public.sale_returns
SET processed_by_name = COALESCE(NULLIF(trim(processed_by_name), ''), 'Usuario'),
    return_date = COALESCE(return_date, created_at::date, current_date)
WHERE processed_by_name IS NULL
   OR trim(processed_by_name) = ''
   OR return_date IS NULL;

ALTER TABLE public.sale_returns
  ALTER COLUMN processed_by_name SET DEFAULT 'Usuario',
  ALTER COLUMN processed_by_name SET NOT NULL,
  ALTER COLUMN return_date SET DEFAULT current_date,
  ALTER COLUMN return_date SET NOT NULL;

ALTER TABLE public.sale_return_items
  ADD COLUMN IF NOT EXISTS negocio_id uuid;

UPDATE public.sale_return_items sri
SET negocio_id = sr.negocio_id
FROM public.sale_returns sr
WHERE sr.id = sri.return_id
  AND sri.negocio_id IS NULL;

ALTER TABLE public.sale_return_items
  ALTER COLUMN negocio_id SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'sale_return_items_negocio_id_fkey'
      AND conrelid = 'public.sale_return_items'::regclass
  ) THEN
    ALTER TABLE public.sale_return_items
      ADD CONSTRAINT sale_return_items_negocio_id_fkey
      FOREIGN KEY (negocio_id)
      REFERENCES public.negocios(id)
      ON DELETE CASCADE;
  END IF;
END;
$$;

CREATE INDEX IF NOT EXISTS sale_returns_business_created_idx
  ON public.sale_returns (negocio_id, created_at DESC);

CREATE INDEX IF NOT EXISTS sale_returns_business_date_idx
  ON public.sale_returns (negocio_id, return_date DESC);

CREATE INDEX IF NOT EXISTS sale_returns_sale_idx
  ON public.sale_returns (sale_id, created_at DESC);

CREATE INDEX IF NOT EXISTS sale_return_items_sale_item_idx
  ON public.sale_return_items (sale_item_id);

CREATE INDEX IF NOT EXISTS sale_return_items_business_idx
  ON public.sale_return_items (negocio_id);

ALTER TABLE public.sale_returns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sale_return_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "sale returns tenant select" ON public.sale_returns;
CREATE POLICY "sale returns tenant select"
  ON public.sale_returns
  FOR SELECT
  TO authenticated
  USING (
    public.is_platform_admin()
    OR negocio_id = public.current_user_negocio_id()
  );

DROP POLICY IF EXISTS "sale return items tenant select" ON public.sale_return_items;
CREATE POLICY "sale return items tenant select"
  ON public.sale_return_items
  FOR SELECT
  TO authenticated
  USING (
    public.is_platform_admin()
    OR negocio_id = public.current_user_negocio_id()
  );

CREATE OR REPLACE FUNCTION public.process_partial_sale_return(
  p_sale_id bigint,
  p_items jsonb,
  p_compensation_method text,
  p_reason text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  current_user_id uuid := auth.uid();
  current_negocio uuid := public.current_user_negocio_id();
  sale_record record;
  item_payload jsonb;
  sale_item_record record;
  return_id_value bigint;
  requested_quantity numeric;
  already_returned numeric;
  available_quantity numeric;
  stock_condition_value text;
  discount_factor numeric;
  gross_amount_value numeric;
  refund_amount_value numeric;
  discount_amount_value numeric;
  refund_total_value numeric := 0;
  restocked_quantity_value numeric := 0;
  damaged_quantity_value numeric := 0;
  next_sale_balance numeric;
  next_client_balance numeric;
  processed_by_name_value text := 'Usuario';
BEGIN
  IF current_user_id IS NULL THEN
    RAISE EXCEPTION 'Usuario no autenticado';
  END IF;

  IF p_sale_id IS NULL THEN
    RAISE EXCEPTION 'La venta es obligatoria';
  END IF;

  IF p_items IS NULL
    OR jsonb_typeof(p_items) <> 'array'
    OR jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION 'Selecciona al menos un producto para devolver';
  END IF;

  IF p_compensation_method IS NULL
    OR p_compensation_method NOT IN ('cash_refund', 'store_credit', 'reduce_debt') THEN
    RAISE EXCEPTION 'El método de compensación no es válido';
  END IF;

  IF length(trim(COALESCE(p_reason, ''))) < 3 THEN
    RAISE EXCEPTION 'Indica el motivo de la devolución';
  END IF;

  SELECT
    v.id,
    v.negocio_id,
    v.cliente_id,
    v.subtotal,
    v.total,
    v.tipo_pago,
    v.saldo_pendiente,
    v.estado
  INTO sale_record
  FROM public.ventas v
  WHERE v.id = p_sale_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Venta no encontrada';
  END IF;

  IF NOT public.is_platform_admin()
    AND (
      current_negocio IS NULL
      OR sale_record.negocio_id <> current_negocio
      OR NOT public.can_manage_current_business()
    ) THEN
    RAISE EXCEPTION 'No tienes permiso para procesar devoluciones';
  END IF;

  IF lower(COALESCE(sale_record.estado, '')) IN ('cancelada', 'cancelled', 'anulada') THEN
    RAISE EXCEPTION 'No se puede devolver una venta anulada';
  END IF;

  SELECT COALESCE(
    NULLIF(to_jsonb(u)->>'nombre', ''),
    NULLIF(to_jsonb(u)->>'full_name', ''),
    NULLIF(to_jsonb(u)->>'username', ''),
    NULLIF(to_jsonb(u)->>'email', ''),
    'Usuario'
  )
  INTO processed_by_name_value
  FROM public.usuarios u
  WHERE u.id = current_user_id;

  processed_by_name_value := COALESCE(processed_by_name_value, 'Usuario');

  IF p_compensation_method IN ('store_credit', 'reduce_debt')
    AND sale_record.cliente_id IS NULL THEN
    RAISE EXCEPTION 'Esta compensación requiere que la venta tenga un cliente registrado';
  END IF;

  IF p_compensation_method IN ('cash_refund', 'store_credit')
    AND COALESCE(sale_record.saldo_pendiente, 0) > 0 THEN
    RAISE EXCEPTION 'La venta tiene deuda pendiente; selecciona reducción de deuda';
  END IF;

  discount_factor := CASE
    WHEN COALESCE(sale_record.subtotal, 0) > 0
      THEN GREATEST(0, COALESCE(sale_record.total, 0) / sale_record.subtotal)
    ELSE 1
  END;

  INSERT INTO public.sale_returns (
    negocio_id,
    sale_id,
    client_id,
    compensation_method,
    reason,
    created_by,
    processed_by_name
  )
  VALUES (
    sale_record.negocio_id,
    sale_record.id,
    sale_record.cliente_id,
    p_compensation_method,
    trim(p_reason),
    current_user_id,
    processed_by_name_value
  )
  RETURNING id INTO return_id_value;

  FOR item_payload IN
    SELECT value FROM jsonb_array_elements(p_items)
  LOOP
    requested_quantity := NULLIF(item_payload->>'quantity', '')::numeric;
    stock_condition_value := lower(trim(COALESCE(item_payload->>'stock_condition', '')));

    IF requested_quantity IS NULL OR requested_quantity <= 0 THEN
      RAISE EXCEPTION 'Todas las cantidades devueltas deben ser mayores que cero';
    END IF;

    IF stock_condition_value IS NULL
      OR stock_condition_value NOT IN ('restock', 'damaged') THEN
      RAISE EXCEPTION 'Indica si cada producto vuelve al stock o está averiado';
    END IF;

    SELECT
      vi.id,
      vi.producto_id,
      vi.cantidad,
      vi.precio,
      COALESCE(p.nombre, 'Producto eliminado') AS product_name
    INTO sale_item_record
    FROM public.venta_items vi
    LEFT JOIN public.productos p ON p.id = vi.producto_id
    WHERE vi.id = NULLIF(item_payload->>'sale_item_id', '')::bigint
      AND vi.venta_id = sale_record.id;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Uno de los productos no pertenece a la venta';
    END IF;

    SELECT COALESCE(SUM(sri.quantity), 0)
    INTO already_returned
    FROM public.sale_return_items sri
    JOIN public.sale_returns sr ON sr.id = sri.return_id
    WHERE sri.sale_item_id = sale_item_record.id
      AND sr.sale_id = sale_record.id;

    available_quantity := COALESCE(sale_item_record.cantidad, 0) - already_returned;

    IF requested_quantity > available_quantity THEN
      RAISE EXCEPTION
        'La cantidad devuelta de % supera las % unidades disponibles',
        sale_item_record.product_name,
        available_quantity;
    END IF;

    IF stock_condition_value = 'restock' AND sale_item_record.producto_id IS NULL THEN
      RAISE EXCEPTION 'No se puede reponer al stock un producto eliminado';
    END IF;

    gross_amount_value := round(requested_quantity * COALESCE(sale_item_record.precio, 0), 2);
    refund_amount_value := round(gross_amount_value * discount_factor, 2);
    discount_amount_value := GREATEST(0, gross_amount_value - refund_amount_value);

    INSERT INTO public.sale_return_items (
      negocio_id,
      return_id,
      sale_item_id,
      product_id,
      product_name,
      quantity,
      stock_condition,
      unit_price,
      gross_amount,
      discount_amount,
      refund_amount
    )
    VALUES (
      sale_record.negocio_id,
      return_id_value,
      sale_item_record.id,
      sale_item_record.producto_id,
      sale_item_record.product_name,
      requested_quantity,
      stock_condition_value,
      COALESCE(sale_item_record.precio, 0),
      gross_amount_value,
      discount_amount_value,
      refund_amount_value
    );

    IF stock_condition_value = 'restock' THEN
      UPDATE public.productos
      SET stock = COALESCE(stock, 0) + requested_quantity
      WHERE id = sale_item_record.producto_id
        AND negocio_id = sale_record.negocio_id;

      IF NOT FOUND THEN
        RAISE EXCEPTION 'No se encontró el producto para reponer su stock';
      END IF;

      restocked_quantity_value := restocked_quantity_value + requested_quantity;
    ELSE
      damaged_quantity_value := damaged_quantity_value + requested_quantity;
    END IF;

    refund_total_value := refund_total_value + refund_amount_value;
  END LOOP;

  IF refund_total_value <= 0 THEN
    RAISE EXCEPTION 'El total de la devolución debe ser mayor que cero';
  END IF;

  IF p_compensation_method = 'reduce_debt' THEN
    IF refund_total_value > COALESCE(sale_record.saldo_pendiente, 0) THEN
      RAISE EXCEPTION
        'La devolución supera la deuda pendiente de la venta. Reduce la cantidad o registra primero el pago correspondiente';
    END IF;

    next_sale_balance := GREATEST(0, COALESCE(sale_record.saldo_pendiente, 0) - refund_total_value);

    UPDATE public.ventas
    SET saldo_pendiente = next_sale_balance,
        estado_credito = CASE
          WHEN next_sale_balance <= 0 THEN 'pagado'
          ELSE 'parcial'
        END
    WHERE id = sale_record.id
      AND negocio_id = sale_record.negocio_id;

    UPDATE public.clientes
    SET saldo = COALESCE(saldo, 0) - refund_total_value
    WHERE id = sale_record.cliente_id
      AND negocio_id = sale_record.negocio_id
    RETURNING saldo INTO next_client_balance;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Cliente no encontrado para reducir la deuda';
    END IF;
  ELSIF p_compensation_method = 'store_credit' THEN
    UPDATE public.clientes
    SET saldo = COALESCE(saldo, 0) - refund_total_value
    WHERE id = sale_record.cliente_id
      AND negocio_id = sale_record.negocio_id
    RETURNING saldo INTO next_client_balance;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Cliente no encontrado para crear el saldo a favor';
    END IF;
  ELSE
    next_sale_balance := COALESCE(sale_record.saldo_pendiente, 0);

    IF sale_record.cliente_id IS NOT NULL THEN
      SELECT saldo
      INTO next_client_balance
      FROM public.clientes
      WHERE id = sale_record.cliente_id
        AND negocio_id = sale_record.negocio_id;
    END IF;
  END IF;

  UPDATE public.sale_returns
  SET refund_total = refund_total_value,
      restocked_quantity = restocked_quantity_value,
      damaged_quantity = damaged_quantity_value
  WHERE id = return_id_value;

  RETURN jsonb_build_object(
    'return_id', return_id_value,
    'sale_id', sale_record.id,
    'refund_total', refund_total_value,
    'restocked_quantity', restocked_quantity_value,
    'damaged_quantity', damaged_quantity_value,
    'compensation_method', p_compensation_method,
    'sale_pending_balance', COALESCE(next_sale_balance, sale_record.saldo_pendiente, 0),
    'client_balance', next_client_balance
  );
END;
$$;

REVOKE ALL ON FUNCTION public.process_partial_sale_return(bigint, jsonb, text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.process_partial_sale_return(bigint, jsonb, text, text) TO authenticated;

GRANT SELECT ON public.sale_returns, public.sale_return_items TO authenticated;

COMMENT ON TABLE public.sale_returns IS
  'Headers for partial returns. Original sales and invoices remain unchanged.';

COMMENT ON FUNCTION public.process_partial_sale_return(bigint, jsonb, text, text) IS
  'Atomically validates a partial return, records it, restores good stock and applies customer compensation.';

NOTIFY pgrst, 'reload schema';
